package com.placement.ui;
import com.placement.sockets.SocketClient;
import javax.swing.*;import javax.swing.border.EmptyBorder;import javax.swing.table.DefaultTableCellRenderer;import javax.swing.table.DefaultTableModel;import javax.swing.table.JTableHeader;import java.awt.*;import java.time.LocalDate;import java.time.temporal.ChronoUnit;
public class StudentDashboard extends JFrame{
 private final String name,email,token;private final SocketClient client=new SocketClient();private final CardLayout cards=new CardLayout();private final JPanel content=new JPanel(cards);private final DefaultTableModel jobs=model(new String[]{"Job ID","Company","Role","Package","Min CGPA","Branches","Backlogs","Year","Deadline"}),apps=model(new String[]{"Job ID","Company","Role","Status","Score","Applied At"}),notes=model(new String[]{"ID","Job ID","Subject","Message","Recipients","Created"});private final JTable jobsT=new JTable(jobs);
 public StudentDashboard(String name,String email,String token){this.name=name==null||name.isBlank()?"Student":name;this.email=email;this.token=token;setTitle("Placement Eligibility Portal - Student Dashboard");setSize(1200,720);setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);setLocationRelativeTo(null);build();refresh();}
 public StudentDashboard(String name,String email){this(name,email,null);}public StudentDashboard(){this("Student","",null);}
 private void build(){JPanel root=new JPanel(new BorderLayout());JPanel side=new JPanel();side.setPreferredSize(new Dimension(210,720));side.setBackground(new Color(20,92,48));side.setBorder(BorderFactory.createEmptyBorder(28,16,18,16));side.setLayout(new BoxLayout(side,BoxLayout.Y_AXIS));JLabel a=new JLabel("PLACEMENT"),b=new JLabel("ELIGIBILITY PORTAL");a.setForeground(Color.WHITE);a.setFont(new Font("SansSerif",Font.BOLD,22));b.setForeground(new Color(220,245,225));b.setFont(new Font("SansSerif",Font.PLAIN,11));side.add(a);side.add(b);side.add(Box.createVerticalStrut(28));nav(side,"Dashboard","D");nav(side,"Placement Drives","J");nav(side,"My Applications","A");nav(side,"Notifications","N");nav(side,"My Profile","P");side.add(Box.createVerticalGlue());nav(side,"Logout",null);root.add(side,BorderLayout.WEST);JPanel main=new JPanel(new BorderLayout());JPanel head=new JPanel(new BorderLayout());head.setBackground(Color.WHITE);head.setBorder(BorderFactory.createEmptyBorder(18,24,18,24));JLabel t=new JLabel("Student Dashboard");t.setFont(new Font("SansSerif",Font.BOLD,22));head.add(t,BorderLayout.WEST);head.add(new JLabel(name),BorderLayout.EAST);main.add(head,BorderLayout.NORTH);content.setBackground(new Color(247,248,245));content.add(dashboard(),"D");content.add(jobsPage(),"J");content.add(appsPage(),"A");content.add(notesPage(),"N");content.add(profile(),"P");main.add(content);root.add(main);setContentPane(root);}
 private void nav(JPanel p,String text,String card){JButton b=new JButton(text);b.setMaximumSize(new Dimension(178,40));b.setAlignmentX(Component.LEFT_ALIGNMENT);b.setHorizontalAlignment(SwingConstants.LEFT);b.setForeground(Color.WHITE);b.setBackground(new Color(20,92,48));b.setBorderPainted(false);b.setFocusPainted(false);if(card==null)b.addActionListener(e->logout());else b.addActionListener(e->{cards.show(content,card);if(card.equals("J"))loadJobs();if(card.equals("A"))loadApps();if(card.equals("N"))loadNotes();});p.add(b);p.add(Box.createVerticalStrut(4));}
 private JPanel dashboard(){JPanel p=page();p.add(label("Welcome, "+name,22,true),BorderLayout.NORTH);p.add(label("View placement drives, apply to jobs and track your applications.",14,false),BorderLayout.CENTER);return p;}
 private JPanel jobsPage(){JPanel p=page();JPanel top=new JPanel(new FlowLayout(FlowLayout.LEFT));top.setOpaque(false);JButton r=button("Refresh"),a=button("Apply to Selected Job");r.addActionListener(e->loadJobs());a.addActionListener(e->apply());top.add(r);top.add(a);p.add(top,BorderLayout.NORTH);style(jobsT);p.add(new JScrollPane(jobsT));return p;}
 private JPanel appsPage(){JPanel p=page();JButton r=button("Refresh");r.addActionListener(e->loadApps());p.add(r,BorderLayout.NORTH);JTable t=new JTable(apps);style(t);p.add(new JScrollPane(t));return p;}
 private JPanel notesPage(){JPanel p=page();JButton r=button("Refresh");r.addActionListener(e->loadNotes());p.add(r,BorderLayout.NORTH);JTable t=new JTable(notes);style(t);p.add(new JScrollPane(t));return p;}
 private JPanel profile(){JPanel p=page();JPanel f=new JPanel(new GridLayout(0,2,8,8));f.setBackground(Color.WHITE);JTextField n=new JTextField(name),e=new JTextField(email==null?"":email);n.setEditable(false);e.setEditable(false);f.add(new JLabel("Name"));f.add(n);f.add(new JLabel("Login ID"));f.add(e);p.add(f,BorderLayout.NORTH);return p;}
 private void refresh(){loadJobs();loadApps();loadNotes();}
 private void loadJobs(){jobs.setRowCount(0);try{SocketClient.ListResponse r=client.sendListRequest("GET_JOBS",token);if(!r.success)throw new Exception(r.errorMessage);for(String l:r.lines){String[]x=l.split("\\|",-1);if(x.length>=10)jobs.addRow(new Object[]{x[0].isBlank()?"-":x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7],formatDeadline(x[9])});}}catch(Exception e){}}
 private void loadApps(){apps.setRowCount(0);try{SocketClient.ListResponse r=client.sendListRequest("GET_MY_APPLICATIONS",token);if(!r.success)return;for(String l:r.lines){String[]x=l.split("\\|",-1);if(x.length>=6)apps.addRow(x);}}catch(Exception e){}}
 private void loadNotes(){notes.setRowCount(0);try{SocketClient.ListResponse r=client.sendListRequest("GET_NOTIFICATIONS",token);if(!r.success)return;for(String l:r.lines){String[]x=l.split("\\|",-1);if(x.length>=7)notes.addRow(new Object[]{x[0],x[1],x[2],x[3],x[5],x[6]});}}catch(Exception e){}}
 private void apply(){int row=jobsT.getSelectedRow();if(row<0){JOptionPane.showMessageDialog(this,"Select a job first.");return;}try{SocketClient.Response r=client.sendRequest("APPLY_JOB",token,String.valueOf(jobsT.getValueAt(row,0)));if(!r.success)throw new Exception(r.payload);JOptionPane.showMessageDialog(this,"Application submitted successfully.");loadApps();}catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}}
 private void logout(){try{client.sendRequest("LOGOUT",token);}catch(Exception ignored){}dispose();new LoginFrame().setVisible(true);}private static JPanel page(){JPanel p=new JPanel(new BorderLayout(0,12));p.setBackground(new Color(247,248,245));p.setBorder(BorderFactory.createEmptyBorder(20,20,20,20));return p;}private static JLabel label(String s,int z,boolean b){JLabel l=new JLabel(s);l.setFont(new Font("SansSerif",b?Font.BOLD:Font.PLAIN,z));l.setForeground(new Color(38,50,43));return l;}private static JButton button(String s){JButton b=new JButton(s);b.setFocusPainted(false);return b;}private static DefaultTableModel model(String[]c){return new DefaultTableModel(c,0){public boolean isCellEditable(int r,int c){return false;}};}private static void style(JTable t){t.setRowHeight(30);t.setAutoCreateRowSorter(true);t.setFillsViewportHeight(true);t.setShowGrid(true);t.setGridColor(new Color(205,212,207));t.setIntercellSpacing(new Dimension(1,1));t.setSelectionBackground(new Color(205,224,211));t.setSelectionForeground(new Color(38,50,43));DefaultTableCellRenderer center=new DefaultTableCellRenderer();center.setHorizontalAlignment(SwingConstants.CENTER);t.setDefaultRenderer(Object.class,center);JTableHeader h=t.getTableHeader();h.setReorderingAllowed(false);h.setPreferredSize(new Dimension(h.getPreferredSize().width,32));h.setDefaultRenderer(new DefaultTableCellRenderer(){{setHorizontalAlignment(SwingConstants.CENTER);setOpaque(true);setBackground(new Color(232,238,234));setForeground(new Color(38,50,43));setBorder(BorderFactory.createMatteBorder(0,0,1,1,new Color(170,180,173)));}});}private static String formatDeadline(String value){if(value==null||value.isBlank())return "-";try{LocalDate d=LocalDate.parse(value.length()>=10?value.substring(0,10):value);long days=ChronoUnit.DAYS.between(LocalDate.now(),d);if(days==0)return "Due today";if(days==1)return "1 day left";if(days>1)return days+" days left";long late=Math.abs(days);return late==1?"Expired 1 day ago":"Expired "+late+" days ago";}catch(Exception e){return value;}}
}
